# Generated by Django 4.0.6 on 2022-08-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('send_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('run_date', models.CharField(max_length=32)),
                ('run_code', models.CharField(max_length=32)),
                ('run_frequency', models.CharField(max_length=32)),
                ('send_person', models.CharField(max_length=32)),
                ('send_room', models.CharField(max_length=32)),
                ('last_result', models.CharField(default='', max_length=32)),
                ('last_run_time', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
