# Generated by Django 4.0.6 on 2022-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_info',
            name='task_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
