# Generated by Django 4.0.6 on 2022-08-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_app', '0003_task_info_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_info',
            name='status',
            field=models.IntegerField(default='1'),
        ),
    ]
